version: '3.1'

services:
  redis:
    container_name: marktplatz-product-service.redis
    image: redis:7
    ports:
      - "6379:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - /tmp:/var/redis/data
    depends_on:
      - postgres

  postgres:
      container_name: marktplatz-product-service.postgres
      image: postgres:16
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: postgres
