spring:
  application:
    name: marktplatz-product-service
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
  jpa:
    show-sql: true
