spring:
  application:
    name: marktplatz-product-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      port: 6379
      host: localhost
      database: 4
  jpa:
    show-sql: true
server:
  port: 62567
  shutdown: GRACEFUL


