version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0


jobs:
  build_image:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 17.0.8-graalce
      - run:
          name: "bootBuildImage"
          command: "./gradlew -Pnative bootBuildImage -DskipTests"
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/push:
          image: maelstrom0x8/mp-product-service
          tag: $CIRCLE_TAG-x86_64

workflows:
  build-native-image:
    jobs:
      - build_image:
          context:
            - aeros-ctx
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
